export type Polroid = {
  img: string;
  top: number;
  left: number;
  index: number;
  rotate: number;
  caption: string;
};

export const Polaroids: Polroid[] = [
  {
    img: '/example-1.jpg',
    top: -2,
    left: 1,
    index: 1,
    rotate: -6,
    caption: 'Light Love',
  },
  {
    img: '/example-2.jpg',
    top: 30,
    left: -1,
    index: 3,
    rotate: 6,
    caption: 'Sunset',
  },
  {
    img: '/example-3.jpg',
    top: 60,
    left: 1,
    index: 1,
    rotate: -6,
    caption: 'Vacation',
  },
  {
    img: '/example-4.jpg',
    top: -4,
    left: 17,
    index: 5,
    rotate: 6,
    caption: 'Anniversary',
  },
  {
    img: '/example-5.jpg',
    top: 30,
    left: 15,
    index: 4,
    rotate: -6,
    caption: 'Walk with me?',
  },
  {
    img: '/example-6.jpg',
    top: 60,
    left: 17,
    index: 3,
    rotate: 6,
    caption: 'London Love',
  },
  {
    img: '/example-7.jpg',
    top: -2,
    left: 32,
    index: 3,
    rotate: -6,
    caption: 'Summer vibe',
  },
  {
    img: '/example-8.jpg',
    top: 30,
    left: 32,
    index: 1,
    rotate: -6,
    caption: 'Summer vibe',
  },
  {
    img: '/example-9.jpg',
    top: 66,
    left: 32,
    index: 1,
    rotate: -6,
    caption: 'Birthday celebrations',
  },
  {
    img: '/example-10.jpg',
    top: 1,
    left: 48,
    index: 8,
    rotate: 6,
    caption: 'Dance with me',
  },
  {
    img: '/example-11.jpg',
    top: 30,
    left: 49,
    index: 1,
    rotate: 6,
    caption: 'Merry me?',
  },
  {
    img: '/example-12.jpg',
    top: 60,
    left: 49,
    index: 10,
    rotate: 6,
    caption: 'Iceland',
  },
  {
    img: '/example-13.jpg',
    top: -2,
    left: 65,
    index: 6,
    rotate: -6,
    caption: 'New York',
  },
  {
    img: '/example-14.jpg',
    top: 30,
    left: 67,
    index: 6,
    rotate: -6,
    caption: 'Antumn',
  },
  {
    img: '/example-15.jpg',
    top: 62,
    left: 67,
    index: 6,
    rotate: 6,
    caption: 'Yoga Time',
  },
  {
    img: '/example-16.jpg',
    top: -2,
    left: 80,
    index: 10,
    rotate: -6,
    caption: 'Movie evening',
  },
  {
    img: '/example-17.jpg',
    top: 30,
    left: 84,
    index: 2,
    rotate: 6,
    caption: 'Light Celebration',
  },
  {
    img: '/example-18.jpg',
    top: 60,
    left: 82,
    index: 9,
    rotate: -6,
    caption: 'Happy Anniversary',
  },
];
